<template>
  <svg
    width="16"
    height="4"
    viewBox="0 0 16 4"
    fill="none"
    aria-hidden="true"
  >
    <circle
      cx="2"
      cy="2"
      r="1.5"
      fill="currentColor"
      stroke="currentColor"
    />
    <circle
      cx="8"
      cy="2"
      r="1.5"
      fill="currentColor"
      stroke="currentColor"
    />
    <circle
      cx="14"
      cy="2"
      r="1.5"
      fill="currentColor"
      stroke="currentColor"
    />
  </svg>
</template>
